Repository BookwooriAlpineClub/Bookwoori-Front, pull requests merged in 2024-10, with the labels that each got.

#4 프로젝트 생성
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug-report-brief.md
  .github/ISSUE_TEMPLATE/bug-report-detail.md
  .github/ISSUE_TEMPLATE/todo.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  public/index.html
  src/Router.tsx
  src/api/폴더업로드를위한파일
  src/assets/icons.ts
  src/components/common/Button.tsx
  src/hooks/폴더업로드를위한파일
  src/index.tsx
  src/pages/notification/NotificationPage.tsx
  src/react-app-env.d.ts
  src/states/atoms.ts
  src/states/selectors.ts
  src/styles/global.ts
  src/styles/mixins.ts
  src/styles/reset.css
  src/styles/theme.ts
  src/tests/폴더업로드를위한파일
  src/types/domain/폴더업로드를위한파일
  src/types/global.d.ts
  src/types/styled.d.ts
  src/utils/formatters.ts
  src/utils/helpers.ts
  src/utils/validators.ts
  tsconfig.json
Labels: development🔨

#10 Spinner 컴포넌트 (공통)
  src/assets/icons/loading.svg
  src/components/common/Spinner.tsx
Labels: design💄

#23 fixed #16
  craco.config.js
  jest.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: help💡

#16 프로젝트 생성 (PWA)
  .eslintignore
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  craco.config.js
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  public/logo_neon.svg
  public/logo_neon_512.png
  public/manifest.json
  public/robots.txt
  public/screenshot_narrow.svg
  public/screenshot_wide.svg
  src/assets/icons.ts
  src/assets/icons/폴더업로드를위한파일
  src/assets/images/폴더업로드를위한파일
  src/index.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  src/styles/global.ts
  src/styles/reset.css
  src/styles/theme.ts
  src/types/styled.d.ts
  tsconfig.json
Labels: setting ⚙

#14 버튼 컴포넌트 (공통)
  .babelrc
  .eslintrc.json
  craco.config.js
  src/components/common/Button.tsx
  src/tests/Common/Button.test.tsx
  tsconfig.path.json
Labels: feature✨, design💄

#25 PR 템플릿, 이슈 템플릿 적용을 위해 merge합니다.
  .babelrc
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug-report-brief.md
  .github/ISSUE_TEMPLATE/bug-report-detail.md
  .github/ISSUE_TEMPLATE/todo.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  craco.config.js
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  public/logo_neon.svg
  public/logo_neon_512.png
  public/manifest.json
  public/robots.txt
  public/screenshot_narrow.svg
  public/screenshot_wide.svg
  src/Router.tsx
  src/api/폴더업로드를위한파일
  src/assets/icons/loading.svg
  src/assets/icons/폴더업로드를위한파일
  src/assets/images/폴더업로드를위한파일
  src/components/common/Button.tsx
  src/components/common/Spinner.tsx
  src/hooks/폴더업로드를위한파일
  src/index.tsx
  src/pages/notification/NotificationPage.tsx
  src/react-app-env.d.ts
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  src/states/atoms.ts
  src/states/selectors.ts
  src/styles/global.ts
  src/styles/mixins.ts
  src/styles/reset.css
  src/styles/theme.ts
  src/tests/Common/Button.test.tsx
  src/tests/폴더업로드를위한파일
  src/types/domain/폴더업로드를위한파일
  src/types/global.d.ts
  src/types/styled.d.ts
  src/utils/formatters.ts
  src/utils/helpers.ts
  src/utils/validators.ts
  tsconfig.json
  tsconfig.path.json
Labels: documentation📝, feature✨

#27 버튼 컴포넌트 (공통)
  src/components/common/Button.tsx
  src/tests/Common/Button.test.tsx
Labels: refactor♻️, design💄
