Repository BookwooriAlpineClub/Bookwoori-Front, pull requests merged in 2024-12, with the labels that each got.

#141 클라이밍 진행 페이지
  src/apis/climbingTemp.ts
  src/components/climbing/ClimbingBoard.tsx
  src/components/climbing/ClimbingRope.tsx
  src/components/climbing/Memo.tsx
  src/components/climbing/MemoDialog.tsx
  src/components/climbing/ProgressBar.tsx
  src/hooks/query/useClimbingProgress.ts
  src/pages/climbing/ClimbingPage.tsx
  src/pages/climbing/ClimbingProgressPage.tsx
  src/types/domain/climbingTemp.ts
Labels: feature✨, development🔨

#159 DM 페이지
  src/apis/chat.ts
  src/apis/messageRoom.ts
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChatMenu.tsx
  src/components/chatting/ChattingListItem.tsx
  src/components/chatting/DateLine.tsx
  src/hooks/query/useDm.ts
  src/pages/channel/foo.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/types/domain/dm.ts
  src/types/domain/messageRoom.ts
  src/utils/formatters.ts
Labels: feature✨, development🔨

#162 헤더 컴포넌트
  src/components/common/Header.tsx
Labels: feature✨, design💄

#163 로그인
  src/apis/auth.ts
  src/apis/interceptor.ts
  src/pages/login/RedirectionPage.tsx
Labels: feature✨, development🔨

#112 책 평가 리스트 페이지
  src/assets/icons/md_star.svg
  src/components/book/ReviewItem.tsx
  src/components/common/Chip.tsx
  src/components/common/Header.tsx
  src/pages/book/ReviewListPage.tsx
  src/router/Router.tsx
  src/styles/mixins.ts
  src/types/apis/book.d.ts
  src/types/apis/record.d.ts
Labels: feature✨, design💄

#132 책 검색 페이지
  src/assets/icons/ck_close.svg
  src/assets/icons/md_outline_search.svg
  src/components/book/BookinfoItem.tsx
  src/pages/book/SearchPage.tsx
  src/router/Router.tsx
  src/types/apis/book.d.ts
Labels: feature✨, design💄

#133 채널 추가 페이지 퍼블리싱 완성
  src/components/channel/SearchBottomsheet.tsx
  src/components/chatting/ChatMenu.tsx
  src/components/common/Bottomsheet.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/router/Router.tsx
Labels: feature✨, design💄

#153 책 기록 리스트 페이지
  src/assets/icons/md_auto_stories.svg
  src/assets/icons/md_star.svg
  src/components/book/RecordListItem.tsx
  src/components/common/Chip.tsx
  src/pages/book/RecordListPage.tsx
  src/router/Router.tsx
  src/types/apis/book.d.ts
Labels: feature✨, design💄

#166 책 검색 상세 페이지, 책 기록 상세 페이지
  .eslintrc.json
  src/assets/icons/ai_outline_delete.svg
  src/assets/icons/ck_arrow_back.svg
  src/assets/icons/edit.svg
  src/assets/icons/fi_save.svg
  src/components/book/BookInfoDetail.tsx
  src/components/book/Fieldset.tsx
  src/components/book/Header.tsx
  src/components/book/InputPage.tsx
  src/components/book/InputPeriod.tsx
  src/components/book/InputReview.tsx
  src/components/common/Tag.tsx
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/router/Router.tsx
  src/styles/reset.css
Labels: feature✨, design💄

#168 책 기록 수정 페이지
  src/assets/icons/done.svg
  src/assets/icons/md_book.svg
  src/components/book/Header.tsx
  src/components/book/InputPage.tsx
  src/components/book/InputPeriod.tsx
  src/components/book/InputReview.tsx
  src/components/book/InputStatus.tsx
  src/pages/book/RecordEditPage.tsx
  src/router/Router.tsx
Labels: feature✨, design💄

#171 🐛 에러 수정
  src/apis/record.ts
  src/components/book/ReviewItem.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/router/Router.tsx
  src/tests/apis/book.test.ts
Labels: bug🐛, development🔨

#172 토스트 띄우기
  src/apis/climbingTemp.ts
  src/apis/interceptor.ts
  src/components/channel/Carousel.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/hooks/query/useClimbingRecruit.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/login/RedirectionPage.tsx
  src/utils/validators.ts
Labels: feature✨, development🔨

#173 🚨 린트 에러 수정
  src/pages/book/ReviewListPage.tsx
  src/states/selectors.ts
Labels: bug🐛, development🔨

#174 간단한 수정
  src/components/channel/Carousel.tsx
  src/components/channel/ChannelItem.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/router/Router.tsx
Labels: bug🐛, refactor♻️, design💄

#176 채널 추가 페이지, 책 검색 페이지 API 연결
  src/apis/book.ts
  src/components/book/BookInfoDetail.tsx
  src/components/book/RecordListItem.tsx
  src/components/book/ReviewItem.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/components/common/InputDropdown.tsx
  src/components/common/InputRadio.tsx
  src/hooks/query/useBook.ts
  src/hooks/query/useChannel.ts
  src/hooks/query/useClimbing.ts
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/pages/book/RecordEditPage.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/pages/book/SearchPage.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/tests/apis/book.test.ts
  src/types/apis/book.d.ts
  src/types/apis/channel.d.ts
  src/types/apis/climbing.d.ts
Labels: feature✨, development🔨

#178 채널 추가 페이지 관련 에러 해결
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/common/InputRadio.tsx
  src/pages/channel/ChannelAddPage.tsx
Labels: bug🐛, development🔨

#179 클라이밍 채널 추가 페이지를 채널 추가 페이지로 통합
  src/router/Router.tsx
Labels: bug🐛, development🔨

#180 서버바 컴포넌트 API 연결
  src/apis/server.ts
  src/components/common/Serverbar.tsx
  src/hooks/query/useServer.ts
  src/states/atoms.ts
  src/states/selectors.ts
  src/types/apis/server.d.ts
  src/types/global.d.ts
Labels: feature✨, development🔨

#185 책 평가 리스트 페이지, 책 기록 리스트 페이지, 책 검색 상세 페이지, 책 기록 상세 페이지 API 연결
  src/apis/book.ts
  src/apis/record.ts
  src/components/book/BookInfoDetail.tsx
  src/components/book/Header.tsx
  src/components/book/RecordListItem.tsx
  src/components/book/ReviewItem.tsx
  src/components/climbing/ReviewShareComponent.tsx
  src/constants/sessionStorage.ts
  src/hooks/query/useBook.ts
  src/hooks/query/useRecord.ts
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/pages/book/RecordEditPage.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/types/apis/book.d.ts
  src/types/apis/climbing.d.ts
  src/types/apis/record.d.ts
Labels: feature✨, development🔨

#186 클라이밍 버그 수정
  src/components/climbing/ClimbingBoard.tsx
  src/components/climbing/ClimbingRope.tsx
Labels: bug🐛
