Repository BookwooriAlpineClub/Bookwoori-Front, pull requests merged in 2024-11, with the labels that each got.

#42 프로젝트 설정
  .babelrc
  .eslintignore
  .eslintrc.json
  .prettierignore
  craco.config.js
  craco.config.ts
  jest.config.js
  jest.setup.tsx
  package-lock.json
  package.json
  src/apis/폴더업로드를위한파일
  src/assets/icons/폴더업로드를위한파일
  src/components/common/Header.tsx
  src/index.tsx
  src/styles/global.ts
  src/styles/theme.ts
  src/tests/common/Button.test.tsx
  src/tests/common/Header.test.tsx
  src/tests/폴더업로드를위한파일
  src/types/styled.d.ts
  tsconfig.json
  tsconfig.path.json
Labels: setting⚙

#34 개인 설정 페이지
  src/assets/icons/camera.svg
  src/assets/icons/edit.svg
  src/assets/icons/flag.svg
  src/assets/icons/trash.svg
  src/assets/images/userSettings/background_default.svg
  src/assets/images/userSettings/profile_default.svg
  src/components/userSettings/ExpList.tsx
  src/components/userSettings/UserProfile.tsx
  src/components/userSettings/UserProfileImg.tsx
  src/hooks/useUploadFile.ts
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/ExpHistoryPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/tests/hooks/useUploadFile.test.ts
  src/tests/userSettings/EditUserInfoPage.test.tsx
Labels: feature✨, design💄

#41 Spinner 컴포넌트 (공통)
  src/assets/icons/spinner.svg
  src/components/common/Spinner.tsx
  src/tests/common/Spinner.test.tsx
Labels: feature✨, design💄

#11 Toast 컴포넌트 (공통)
  public/index.html
  src/components/common/Toast.tsx
  src/hooks/useToast.ts
  src/index.tsx
  src/states/atoms.ts
  src/tests/common/Toast.test.tsx
  src/types/global.d.ts
Labels: feature✨, design💄

#12 Dialog 컴포넌트 (공통)
  public/index.html
  src/components/common/Dialog.tsx
  src/components/common/Scrim.tsx
  src/hooks/useDialog.ts
  src/hooks/useModal.ts
  src/index.tsx
  src/states/atoms.ts
  src/tests/common/Dialog.test.tsx
  src/types/global.d.ts
Labels: feature✨, design💄

#13 Bottomsheet 컴포넌트 (공통)
  src/components/common/Bottomsheet.tsx
  src/hooks/useBottomsheet.ts
  src/index.tsx
  src/states/atoms.ts
  src/tests/common/Bottomsheet.test.tsx
Labels: feature✨, design💄

#51 버튼 컴포넌트 (공통)
  src/components/common/Button.tsx
Labels: bug🐛, design💄

#43 채널 추가 페이지
  src/assets/icons/category_add.svg
  src/assets/icons/channel_add.svg
  src/assets/icons/check_circle.svg
  src/assets/icons/down_arrow.svg
  src/assets/icons/hash.svg
  src/assets/icons/run.svg
  src/assets/icons/voice.svg
  src/assets/images/channel/carousel_btn.svg
  src/components/common/Fieldset.tsx
  src/components/common/InputDatepicker.tsx
  src/components/common/InputDropdown.tsx
  src/components/common/InputRadio.tsx
  src/components/common/InputText.tsx
  src/pages/channel/CategoryAddPage.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/styles/global.ts
  src/styles/mixins.ts
  src/styles/reset.css
  src/types/global.d.ts
  src/utils/formatters.ts
Labels: feature✨, design💄

#52 BadgeListItem 컴포넌트 (공통)
  src/components/common/BadgeListItem.tsx
Labels: feature✨, design💄

#53 InputField 컴포넌트, TextAreaField 컴포넌트, TitleAndFieldContainer 컴포넌트 (공통)
  .gitignore
  src/assets/icons/bi_crown.svg
  src/assets/icons/bi_user_plus.svg
  src/assets/icons/fi_log_out.svg
  src/assets/icons/fi_settings.svg
  src/assets/icons/fi_trash_2.svg
  src/components/common/CommunityButton.tsx
  src/components/common/InputField.tsx
  src/components/common/TextAreaField.tsx
  src/components/common/TitleAndFieldContainer.tsx
  src/components/communityinfosetting/CommunityInfoSection.tsx
  src/components/communityinfosetting/CommunitySettingSection.tsx
  src/components/communityinfosetting/SectionContainer.tsx
  src/pages/communityinfosetting/CommunityInfoSettingPage.tsx
  src/tests/common/CommunityButton.test.tsx
  src/tests/communityinfosetting/CommunityInfoSection.test.tsx
  src/tests/communityinfosetting/CommunitySettingSection.test.tsx
  src/tests/utils/renderWithProvider.setup.tsx
  src/utils/helpers.ts
Labels: feature✨, design💄

#60 글로벌스타일 svw&svh/vw&vh 병기
  src/styles/global.ts
Labels: refactor♻️, design💄

#39 공동체 정보 및 설정 보기 페이지
  src/components/common/CommunityInfoCard.tsx
  src/components/communityinfosetting/CommunityInfoSection.tsx
  src/components/communityinfosetting/CommunitySettingSection.tsx
Labels: feature✨, design💄

#37 채팅 페이지 (개인)
  src/assets/icons/copy.svg
  src/assets/icons/send.svg
  src/assets/icons/send_green.svg
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChatMenu.tsx
  src/components/chatting/ChattingListItem.tsx
  src/components/chatting/DateLine.tsx
  src/components/common/Header.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
Labels: feature✨, design💄

#77 SubButton 컴포넌트 타입 수정
  src/components/common/SubButton.tsx
Labels: bug🐛, development🔨

#87 클라이밍 설명 컴포넌트
  package-lock.json
  package.json
  src/components/climbing/ClimbingDescription.tsx
  src/components/climbing/ClimbingDetail.tsx
  src/components/climbing/ClimbingSummary.tsx
  src/components/common/Accordions.tsx
  src/index.tsx
  src/styles/muiTheme.ts
Labels: feature✨, design💄

#83 로그인 페이지
  src/assets/images/login/bookwoori_logo.svg
  src/assets/images/login/kakao_login.svg
  src/pages/login/LoginPage.tsx
Labels: feature✨, design💄

#71 클라이밍 모집 리스트 바텀시트 컴포넌트
  src/assets/icons/edit.svg
  src/assets/icons/hi_outline_plus.svg
  src/assets/icons/md_book.svg
  src/assets/icons/md_check.svg
  src/assets/icons/md_directions_walk.svg
  src/assets/icons/md_group.svg
  src/assets/icons/md_insert_invitation.svg
  src/assets/images/channel/carousel_more_btn.svg
  src/components/channel/Carousel.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/pages/channel/ChannelListPage.tsx
Labels: feature✨, design💄

#88 Popover 컴포넌트 (공통)
  src/components/common/Popover.tsx
  src/hooks/usePopover.ts
Labels: feature✨, design💄

#63 공동체 추가 페이지, useUploadFile 훅
  package.json
  src/assets/icons/fi_arrow_right.svg
  src/assets/icons/md_camera_alt.svg
  src/components/addcommunity/AddCommunityButton.tsx
  src/components/addcommunity/ImageUploadField.tsx
  src/components/addcommunity/IntroSection.tsx
  src/hooks/useUploadFile.ts
  src/pages/addcommunity/AddCommunityPage.tsx
  src/pages/addcommunity/CheckInvitedCommunityPage.tsx
  src/pages/addcommunity/CreateNewCommunityPage.tsx
  src/pages/addcommunity/EnterInvitationPage.tsx
Labels: feature✨, development🔨

#66 버튼 컴포넌트, 버튼 배경 컴포넌트 (공통)
  src/components/common/Button.tsx
  src/components/common/ButtonBackground.tsx
Labels: feature✨, design💄

#84 채팅 바텀시트 컴포넌트
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChatMenu.tsx
  src/hooks/useLongPress.ts
  src/pages/chatting/ChattingPage.tsx
Labels: feature✨, design💄

#85 채널 리스트 페이지, 채널 편집 페이지
  src/assets/icons/trash.svg
  src/components/channel/Accordion.tsx
  src/components/channel/ChannelItem.tsx
  src/components/channel/ChannelList.tsx
  src/components/channel/DeleteConfirmModal.tsx
  src/hooks/useDraggable.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/channel/ChannelListEditPage.tsx
  src/pages/channel/ChannelListPage.tsx
Labels: refactor♻️, design💄

#61 알림 페이지
  src/components/common/BadgeListItem.tsx
  src/components/notification/NotiItem.tsx
  src/pages/notification/NotificationPage.tsx
  src/types/global.d.ts
  src/utils/formatters.ts
Labels: feature✨, design💄

#74 라우팅 설정
  package-lock.json
  package.json
  src/Router.tsx
  src/constants/routePath.ts
  src/hooks/useEncodedNavigate.ts
  src/hooks/useRoaderData.ts
  src/index.tsx
  src/pages/RouterExampleDetailPage.tsx
  src/pages/RouterExamplePage.tsx
  src/router/Router.tsx
  src/router/loader.ts
  src/utils/formatters.ts
  src/utils/validators.ts
  tsconfig.json
Labels: feature✨, development🔨

#95 라우터 children 변경
  src/router/Router.tsx
Labels: bug🐛, development🔨

#121 캐러셀 타입 누락 임의 해결
  src/pages/channel/ChannelListPage.tsx
Labels: bug🐛, development🔨

#110 유저 설정 페이지
  src/apis/auth.ts
  src/apis/member.ts
  src/assets/icons/flag.svg
  src/components/addcommunity/ImageUploadField.tsx
  src/components/channel/ChannelItem.tsx
  src/components/common/DeleteConfirmModal.tsx
  src/components/userSettings/UserProfile.tsx
  src/components/userSettings/UserProfileImg.tsx
  src/hooks/query/useMember.ts
  src/hooks/useUploadFile.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/router/Router.tsx
  src/states/atoms.ts
  src/tests/hooks/useUploadFile.test.ts
  src/types/domain/member.ts
  src/utils/formatters.ts
Labels: feature✨, development🔨

#118 Category API, MessageRoom API
  src/apis/category.ts
  src/apis/messageRoom.ts
  src/types/domain/category.ts
  src/types/domain/messageRoom.ts
Labels: feature✨, development🔨

#72 서버바 컴포넌트 (공통)
  src/assets/icons/bell.svg
  src/assets/icons/chat.svg
  src/assets/icons/library.svg
  src/assets/icons/plus.svg
  src/assets/icons/settings.svg
  src/components/common/Serverbar.tsx
  src/hooks/useServerbar.ts
  src/states/atoms.ts
  src/states/selectors.ts
  src/types/global.d.ts
Labels: feature✨, design💄

#126 라우터 코드 중 파서 에러 해결 (#125)
  src/router/Router.tsx
Labels: bug🐛, development🔨

#129 라우팅 페이지 연결
  src/components/common/InputRadio.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/router/Router.tsx
Labels: feature✨, development🔨

#109 모집 중인 클라이밍
  src/apis/climbingTemp.ts
  src/components/channel/Carousel.tsx
  src/components/climbing/ParticipantList.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/hooks/query/useClimbing.ts
  src/hooks/query/useClimbingRecruit.ts
  src/hooks/useCustomNavigate.ts
  src/index.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/router/Router.tsx
  src/types/domain/climbingTemp.ts
Labels: feature✨, development🔨

#103 API 도메인 파일 + 타입
  craco.config.ts
  src/apis/book.ts
  src/apis/channel.ts
  src/apis/notification.ts
  src/apis/record.ts
  src/tests/apis/book.test.ts
  src/types/apis/book.d.ts
  src/types/apis/channel.d.ts
  src/types/apis/notification.d.ts
  src/types/apis/record.d.ts
  tsconfig.json
Labels: feature✨, development🔨

#143 유저 설정 페이지
  src/apis/channelTemp.ts
  src/apis/member.ts
  src/components/channel/ChannelList.tsx
  src/components/userSettings/UserProfile.tsx
  src/hooks/query/useMember.ts
  src/pages/climbing/ClimbingPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/router/Router.tsx
  src/styles/mixins.ts
  src/types/apis/channel.d.ts
  src/types/domain/channel.ts
  src/types/domain/member.ts
Labels: bug🐛, development🔨

#67 공동체 사이드바 컴포넌트, useCopyToClipboard 훅, SubButton 컴포넌트
  src/assets/icons/md_outline_auto_stories.svg
  src/assets/icons/md_outline_chat_bubble.svg
  src/components/common/CommunityButton.tsx
  src/components/common/Header.tsx
  src/components/communitysidebar/CommunitySideBar.tsx
  src/components/communitysidebar/ProfileModal.tsx
  src/hooks/useCopyToClipboard.ts
  src/hooks/useSideBar.ts
  src/states/atoms.ts
  src/types/global.d.ts
Labels: feature✨, design💄

#144 웹소켓, Stomp 연결
  package-lock.json
  package.json
  src/apis/chat.ts
  src/pages/channel/ChannelPage.tsx
  src/pages/channel/foo.tsx
  src/types/apis/chat.d.ts
Labels: feature✨, development🔨
