Repository BookwooriAlpineClub/Bookwoori-Front, pull requests merged in 2025-01, with the labels that each got.

#197 라우팅 페이지 연결
  src/router/Router.tsx
Labels: feature✨, development🔨

#214 타입 폴더 정리
  src/components/common/Bottomsheet.tsx
  src/components/common/Dialog.tsx
  src/components/common/Fieldset.tsx
  src/components/common/InputDatepicker.tsx
  src/components/common/InputDropdown.tsx
  src/components/common/InputRadio.tsx
  src/components/common/InputText.tsx
  src/components/common/Scrim.tsx
  src/components/common/Serverbar.tsx
  src/components/communitysidebar/CommunitySideBar.tsx
  src/hooks/useModal.ts
  src/hooks/useToast.ts
  src/states/atoms.ts
  src/types/apis/climbing.ts
  src/types/apis/server.ts
  src/types/global.d.ts
  src/types/modal.ts
  src/types/modules/axios.d.ts
  src/types/modules/styled.d.ts
Labels: refactor♻️, development🔨

#217 API 타입: book, record, notification
  src/types/apis/book.ts
  src/types/apis/notification.ts
  src/types/apis/record.ts
  src/types/global.d.ts
Labels: refactor♻️, development🔨

#218 타입 수정사항 반영
  src/apis/book.ts
  src/apis/notification.ts
  src/apis/record.ts
  src/components/book/BookInfoDetail.tsx
  src/components/book/BookinfoItem.tsx
  src/components/book/InputStatus.tsx
  src/components/book/RecordListItem.tsx
  src/components/book/ReviewItem.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/components/common/InputRadio.tsx
  src/hooks/query/useBook.ts
  src/hooks/query/useRecord.ts
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/pages/book/RecordEditPage.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/pages/book/SearchPage.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/tests/apis/book.test.ts
Labels: refactor♻️, development🔨

#230 공통 컴포넌트: 파일명 변경, 파일 이동
  src/components/chatting/ChattingListItem.tsx
  src/components/common/DateLine.tsx
  src/components/common/StatusBadgeListItem.tsx
  src/components/common/UserProfile.tsx
  src/components/communitysidebar/ProfileModal.tsx
  src/components/notification/NotiItem.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/userSettings/SettingsPage.tsx
Labels: refactor♻️, design💄

#236 공통 컴포넌트: Header
  src/components/common/Header.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/channel/ChannelPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/climbing/ClimbingProgressPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/styles/theme.ts
Labels: refactor♻️, design💄

#241 공통 컴포넌트: Segmented Button
  src/components/common/SegmentedButton.tsx
  src/styles/theme.ts
Labels: refactor♻️, design💄

#242 공통 컴포넌트: ExpandableList
  .eslintrc.json
  src/components/common/ExpandableList.tsx
Labels: refactor♻️, design💄

#240 공통 컴포넌트: Emogi, EmogiList
  src/assets/icons/hi_face_smile.svg
  src/components/common/EmojiItem.tsx
  src/components/common/EmojiList.tsx
  src/constants/constants.ts
Labels: refactor♻️, design💄

#210 상수 정의, ESLint 규칙 수정, API response 타입 설정
  src/apis/authClient.ts
  src/apis/client.ts
  src/constants/constants.ts
  src/constants/env.ts
  src/constants/status.ts
  src/pages/channel/ChannelAddPage.tsx
  src/pages/login/LoginPage.tsx
  src/types/apis/apiResponse.ts
  src/types/apis/climbing.ts
Labels: refactor♻️, development🔨

#232 공통 컴포넌트: Accordion
  src/assets/icons/hi_outline_chevron_down.svg
  src/components/common/Accordion.tsx
  src/pages/channel/ChannelListPage.tsx
Labels: refactor♻️, design💄

#237 공통 컴포넌트: 이모지 바텀시트 컴포넌트
  src/components/channel/ChannelChatItem.tsx
  src/components/chatting/ChatItem.tsx
  src/components/common/EmojiBottomsheet.tsx
  src/components/common/IconButton.tsx
Labels: refactor♻️, design💄

#226 공통 컴포넌트: Chip + Tag
  src/components/common/Chip.tsx
  src/components/common/Tag.tsx
Labels: refactor♻️, design💄

#244 svg 파일의 이름과 fill 속성값 수정
  src/assets/icons/bi_book_add.svg
  src/assets/icons/bi_crown.svg
  src/assets/icons/bi_hash.svg
  src/assets/icons/bi_run.svg
  src/assets/icons/bi_user_plus.svg
  src/assets/icons/camera.svg
  src/assets/icons/ck_arrow_back.svg
  src/assets/icons/ck_arrow_right.svg
  src/assets/icons/ck_arrow_up.svg
  src/assets/icons/climber.svg
  src/assets/icons/climber_grey.svg
  src/assets/icons/climbing_flag_before.svg
  src/assets/icons/climbing_flag_color.svg
  src/assets/icons/climbing_flag_done.svg
  src/assets/icons/climbing_flag_outline.svg
  src/assets/icons/fi_arrow_left.svg
  src/assets/icons/fi_arrow_right.svg
  src/assets/icons/fi_bell.svg
  src/assets/icons/fi_log_out.svg
  src/assets/icons/fi_menu.svg
  src/assets/icons/fi_settings.svg
  src/assets/icons/fi_trash_2.svg
  src/assets/icons/fi_users.svg
  src/assets/icons/hi_face_smile.svg
  src/assets/icons/hi_outline_chevron_down.svg
  src/assets/icons/hi_outline_flag.svg
  src/assets/icons/hi_outline_pencil.svg
  src/assets/icons/hi_outline_plus.svg
  src/assets/icons/hi_outline_volume_up.svg
  src/assets/icons/left_arrow.svg
  src/assets/icons/library.svg
  src/assets/icons/md_camera_alt.svg
  src/assets/icons/md_camera_enhance.svg
  src/assets/icons/md_check.svg
  src/assets/icons/md_check_circle.svg
  src/assets/icons/md_collection_bookmark.svg
  src/assets/icons/md_directions_walk.svg
  src/assets/icons/md_group.svg
  src/assets/icons/md_insert_invitation.svg
  src/assets/icons/md_outline_auto_stories.svg
  src/assets/icons/md_outline_chat_bubble.svg
  src/assets/icons/md_outline_chat_bubble_outline.svg
  src/assets/icons/md_outline_content_copy.svg
  src/assets/icons/md_outline_playlist_add.svg
  src/assets/icons/menu.svg
  src/assets/icons/plus.svg
  src/assets/icons/send.svg
  src/assets/icons/send_green.svg
  src/assets/icons/settings.svg
  src/assets/icons/spinner.svg
  src/assets/icons/users.svg
Labels: refactor♻️, design💄

#245 에러 핸들링 공통 로직
  package-lock.json
  package.json
  src/apis/interceptor.ts
  src/components/errorBoundary/ErrorCatcher.tsx
  src/components/errorBoundary/RootErrorBoundary.tsx
  src/components/queryClient/QueryClientBoundary.tsx
  src/constants/constants.ts
  src/errors/RequestError.ts
  src/index.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingPage.tsx
  src/pages/fallback/ErrorPage.tsx
  src/pages/fallback/LoadingPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/router/Router.tsx
  src/states/atoms.ts
  src/types/apis/apiResponse.ts
  src/utils/validators.ts
Labels: feature✨, development🔨

#267 로직별 타입: server, climb/API 타입: server, climb 리팩토링
  .eslintrc.json
  src/apis/server.ts
  src/types/apis/climbing.ts
  src/types/apis/server.ts
  src/types/climbing.ts
  src/types/server.ts
Labels: refactor♻️, development🔨

#265 공통 컴포넌트: 토스트
  src/assets/icons/toast_error.svg
  src/assets/icons/toast_info.svg
  src/assets/icons/toast_success.svg
  src/components/common/Toast.tsx
  src/hooks/useToast.ts
  src/types/modal.ts
Labels: refactor♻️, design💄

#262 프로필 컴포넌트
  src/apis/member.ts
  src/components/channel/ChannelChatItem.tsx
  src/components/common/UserProfile.tsx
  src/components/userSettings/UserProfileImg.tsx
  src/hooks/query/auth.ts
  src/hooks/query/member.ts
  src/hooks/query/useMember.ts
  src/hooks/useUploadFile.ts
  src/pages/library/LibraryHomePage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/types/apis/member.ts
  src/utils/formatters.ts
  src/utils/helpers.ts
  src/utils/validators.ts
Labels: bug🐛, development🔨

#268 채팅 페이지
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/common/Header.tsx
  src/hooks/query/chat.ts
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/utils/formatters.ts
Labels: bug🐛, development🔨

#271 Section 컴포넌트 background-color
  src/components/common/Section.tsx
  src/styles/reset.css
Labels: bug🐛, design💄

#272 InputText 컴포넌트 글자수표시 수정
  src/components/common/InputText.tsx
Labels: bug🐛, design💄

#280 React-Query 훅
  src/apis/record.ts
  src/apis/server.ts
  src/hooks/query/book.ts
  src/hooks/query/device.ts
  src/hooks/query/record.ts
  src/hooks/query/server.ts
  src/hooks/query/useBook.ts
  src/hooks/query/useRecord.ts
  src/hooks/query/useServer.ts
Labels: refactor♻️, development🔨

#275 클라이밍, 채널 리스트 관련 수정
  src/apis/climbing.ts
  src/apis/climbingTemp.ts
  src/components/channel/ChannelItem.tsx
  src/components/channel/ChannelList.tsx
  src/components/climbing/ClimbingBoard.tsx
  src/components/climbing/ClimbingRope.tsx
  src/components/climbing/Memo.tsx
  src/components/climbing/MemoDialog.tsx
  src/components/climbing/ProgressBar.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/common/Accordion.tsx
  src/constants/constants.ts
  src/hooks/query/category.ts
  src/hooks/query/channel.ts
  src/hooks/query/climbing.ts
  src/hooks/query/useCategory.ts
  src/hooks/query/useChannel.ts
  src/hooks/query/useClimbing.ts
  src/hooks/query/useClimbingProgress.ts
  src/hooks/query/useClimbingRecruit.ts
  src/hooks/useDraggable.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/climbing/ClimbingProgressPage.tsx
  src/states/atoms.ts
  src/types/apis/climbing.ts
  src/types/category.ts
  src/types/climbing.ts
  src/types/domain/climbingTemp.ts
  src/types/domain/member.ts
  src/utils/formatters.ts
  src/utils/validators.ts
Labels: development🔨

#282 useModal 훅
  src/hooks/useBottomsheet.ts
  src/hooks/useDialog.ts
  src/hooks/useModal.ts
  src/hooks/useServerbar.ts
  src/hooks/useSideBar.ts
  src/states/atoms.ts
  src/types/modal.ts
Labels: refactor♻️, development🔨

#283 폴더 업로드용 임시파일 삭제하기
  src/apis/폴더업로드를위한파일
  src/assets/images/폴더업로드를위한파일
  src/hooks/폴더업로드를위한파일
Labels: documentation📝, refactor♻️

#286 에러 핸들링 수정, useModal 사용 수정
  src/apis/auth.ts
  src/apis/interceptor.ts
  src/components/channel/Carousel.tsx
  src/components/chatting/ChatItem.tsx
  src/components/climbing/Memo.tsx
  src/components/common/Header.tsx
  src/components/errorBoundary/ErrorCatcher.tsx
  src/components/queryClient/QueryClientBoundary.tsx
  src/constants/constants.ts
  src/errors/RequestError.ts
  src/hooks/useUploadFile.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/SettingsPage.tsx
Labels: refactor♻️, development🔨

#289 디자인 토큰, 공통 컴포넌트, 리액트 쿼리 훅, 타입 수정사항 반영
  src/components/book/BookInfoDetail.tsx
  src/components/book/BookinfoItem.tsx
  src/components/book/Fieldset.tsx
  src/components/book/Header.tsx
  src/components/book/InputPage.tsx
  src/components/book/InputPeriod.tsx
  src/components/book/InputReview.tsx
  src/components/book/InputStatus.tsx
  src/components/book/RecordListItem.tsx
  src/components/book/ReviewItem.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/components/common/Bottomsheet.tsx
  src/components/common/Dialog.tsx
  src/components/common/InputDatepicker.tsx
  src/components/common/InputDropdown.tsx
  src/components/common/InputRadio.tsx
  src/components/common/Scrim.tsx
  src/components/common/Section.tsx
  src/components/common/Serverbar.tsx
  src/components/common/StatusBadgeListItem.tsx
  src/components/common/Tag.tsx
  src/components/communitysidebar/CommunitySideBar.tsx
  src/hooks/query/category.ts
  src/hooks/query/device.ts
  src/hooks/query/server.ts
  src/hooks/useModal.ts
  src/hooks/useToast.ts
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/pages/book/RecordEditPage.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/pages/book/SearchPage.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/pages/notification/NotificationPage.tsx
  src/states/atoms.ts
  src/styles/theme.ts
  src/tests/common/Toast.test.tsx
  src/types/modal.ts
  src/types/toast.ts
Labels: refactor♻️, development🔨

#291 useModal async 작동 개선
  src/hooks/useModal.ts
Labels: refactor♻️, development🔨

#293 `useModal` 훅 수정사항 반영
  src/components/channel/Carousel.tsx
  src/components/channel/ChannelChatItem.tsx
  src/components/chatting/ChatItem.tsx
  src/components/climbing/Memo.tsx
  src/components/common/Bottomsheet.tsx
  src/components/common/Dialog.tsx
  src/components/common/Header.tsx
  src/components/common/Serverbar.tsx
  src/components/communitysidebar/CommunitySideBar.tsx
  src/components/communitysidebar/ProfileModal.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/pages/channel/ChannelEditPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/tests/common/Bottomsheet.test.tsx
  src/tests/common/Dialog.test.tsx
Labels: refactor♻️, development🔨
