Repository BookwooriAlpineClub/Bookwoori-Front, pull requests merged in 2025-02, with the labels that each got.

#298 svg 아이콘 수정사항 반영
  src/assets/icons/bi_crown.svg
  src/assets/icons/bi_hash.svg
  src/assets/icons/bi_run.svg
  src/assets/icons/bi_user_plus.svg
  src/assets/icons/climbing_flag_color.svg
  src/assets/icons/climbing_flag_outline.svg
  src/assets/icons/fi_arrow_left.svg
  src/assets/icons/fi_bell.svg
  src/assets/icons/fi_log_out.svg
  src/assets/icons/fi_settings.svg
  src/assets/icons/fi_trash_2.svg
  src/assets/icons/hi_outline_flag.svg
  src/assets/icons/hi_outline_plus.svg
  src/assets/icons/hi_outline_volume_up.svg
  src/assets/icons/md_check_circle.svg
  src/assets/icons/md_collection_bookmark.svg
  src/assets/icons/md_outline_auto_stories.svg
  src/assets/icons/md_outline_chat_bubble_outline.svg
  src/assets/icons/md_outline_content_copy.svg
  src/assets/icons/toast_error.svg
  src/assets/icons/toast_info.svg
  src/assets/icons/toast_success.svg
  src/components/book/Header.tsx
  src/components/book/InputReview.tsx
  src/components/book/InputStatus.tsx
  src/components/book/RecordListItem.tsx
  src/components/channel/ChannelItem.tsx
  src/components/chatting/ChatMenu.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/common/Header.tsx
  src/components/common/IconButton.tsx
  src/components/common/Serverbar.tsx
  src/components/common/Spinner.tsx
  src/components/common/Toast.tsx
  src/components/communitysidebar/CommunitySideBar.tsx
  src/components/library/BookButton.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/library/LibraryHomePage.tsx
Labels: refactor♻️, design💄

#295 ReviewListItem 컴포넌트 스타일 개편
  src/components/book/BookDetail.tsx
  src/components/book/BookListItem.tsx
  src/components/book/ReviewItem.tsx
  src/components/book/ReviewListItem.tsx
  src/components/book/StarReview.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/components/climbing/ReviewBoard.tsx
  src/components/climbing/ReviewShareComponent.tsx
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordDetailPage.tsx
  src/pages/book/RecordEditPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/pages/book/SearchPage.tsx
  src/types/apis/record.ts
Labels: refactor♻️, design💄

#299 클라이밍 감상평 & 공감 기능 업데이트
  src/apis/climbing.ts
  src/components/addcommunity/ImageUploadField.tsx
  src/components/climbing/ClimbingDescription.tsx
  src/components/climbing/ClimbingDetail.tsx
  src/components/climbing/ClimbingSummary.tsx
  src/components/climbing/EmojiBottomSheet.tsx
  src/components/climbing/ReviewBoard.tsx
  src/components/climbing/ReviewItem.tsx
  src/components/climbing/ReviewShareComponent.tsx
  src/components/common/EmojiItem.tsx
  src/components/common/EmojiList.tsx
  src/components/common/UserAvatar.tsx
  src/components/library/MountainImage.tsx
  src/constants/constants.ts
  src/hooks/query/climbing.ts
  src/hooks/useCopyToClipboard.ts
  src/pages/addcommunity/CreateNewCommunityPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/types/apis/climbing.ts
Labels: feature✨, refactor♻️, development🔨

#300 채팅 답장, 수정, 삭제 기능
  src/apis/chat.ts
  src/assets/icons/multiply.svg
  src/assets/icons/response.svg
  src/assets/images/chat/reply_line.svg
  src/components/channel/ChannelChatItem.tsx
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChatMenu.tsx
  src/components/common/DeleteConfirmModal.tsx
  src/components/common/EmojiBottomsheet.tsx
  src/hooks/query/chat.ts
  src/hooks/useChatHandler.ts
  src/hooks/useUploadFile.ts
  src/pages/chatting/ChattingPage.tsx
  src/states/atoms.ts
  src/types/apis/chat.ts
  src/types/apis/climbing.ts
Labels: feature✨, development🔨

#303 컴파일 에러 수정
  src/components/common/EmojiBottomsheet.tsx
  src/hooks/query/climbing.ts
Labels: bug🐛

#305 Bottomsheet 컴포넌트 HandleBar `border-radius` 수정
  src/components/common/Bottomsheet.tsx
Labels: bug🐛, design💄

#306 Tag 컴포넌트 `onClick` props 추가
  src/components/common/Tag.tsx
Labels: feature✨, development🔨

#307 Identifier 'Toast' has already been declared.
  src/components/common/Toast.tsx
Labels: bug🐛, development🔨

#273 라우터 구조 변경 (중첩 라우틱 적용, 레이아웃 믹스인 포함)
  src/router/Layout.tsx
  src/router/Router.tsx
  src/styles/Layout.ts
Labels: refactor♻️, development🔨

#270 레이아웃 믹스인
  src/components/climbing/ReviewShareComponent.tsx
  src/pages/addcommunity/AddCommunityPage.tsx
  src/pages/addcommunity/CheckInvitedCommunityPage.tsx
  src/pages/addcommunity/CreateNewCommunityPage.tsx
  src/pages/addcommunity/EnterInvitationPage.tsx
  src/pages/book/BookDetailPage.tsx
  src/pages/book/RecordListPage.tsx
  src/pages/book/ReviewListPage.tsx
  src/pages/channel/CategoryAddPage.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/pages/channel/ChannelEditPage.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/channel/ChannelPage.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/climbing/ClimbingProgressPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/pages/communityinfosetting/CommunityInfoSettingPage.tsx
  src/pages/fallback/ErrorPage.tsx
  src/pages/fallback/LoadingPage.tsx
  src/pages/library/LibraryHomePage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/RedirectionPage.tsx
  src/pages/notification/NotificationPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/ExpHistoryPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
  src/styles/Layout.ts
  src/styles/global.ts
  src/styles/mixins.ts
Labels: refactor♻️, design💄

#311 컴파일 에러 해결
  src/components/channel/ChannelChatBar.tsx
  src/components/channel/SearchBottomsheet.tsx
  src/components/chatting/ChatBar.tsx
  src/components/common/Accordion.tsx
  src/components/common/Accordions.tsx
  src/components/common/ExpandableList.tsx
  src/components/common/Header.tsx
  src/components/common/button/IconButton.tsx
  src/components/common/input/ImageField.tsx
  src/components/common/modal/Bottomsheet.tsx
  src/components/common/modal/Dialog.tsx
  src/components/common/modal/GlobalDrawer.tsx
  src/components/library/MountainImage.tsx
  src/hooks/useDraggable.ts
  src/hooks/usePopover.ts
  src/pages/addcommunity/CheckInvitedCommunityPage.tsx
  src/pages/addcommunity/CreateNewCommunityPage.tsx
  src/pages/addcommunity/EnterInvitationPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/pages/communityinfosetting/CommunityInfoSettingPage.tsx
  src/pages/library/RecordListPage.tsx
  src/pages/library/ReviewListPage.tsx
  src/pages/library/SearchPage.tsx
  src/router/Layout.tsx
  src/tests/utils/renderWithProvider.setup.tsx
Labels: bug🐛, development🔨

#317 채팅 페이지 공감 기능 (DM)
  .eslintrc.json
  src/components/channel/ChannelChatItem.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/EmojiList.tsx
  src/components/common/emoji/ChattingBottomsheet.tsx
  src/hooks/useChatHandler.ts
  src/types/apis/chat.ts
  src/types/chat.ts
Labels: feature✨, development🔨

#326 컴파일 에러 해결
  src/hooks/useChatHandler.ts
Labels: bug🐛, development🔨

#319 채팅, 클라이밍 진행
  .eslintrc.json
  src/assets/icons/climbing_flag_color.svg
  src/assets/icons/climbing_flag_outline.svg
  src/assets/icons/flag.svg
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/DateLine.tsx
  src/components/climbing/ClimbingBoard.tsx
  src/components/climbing/ClimbingRope.tsx
  src/components/climbing/ParticipantList.tsx
  src/components/climbing/ProgressBar.tsx
  src/hooks/query/member.ts
  src/hooks/useChatHandler.ts
  src/hooks/useChatScroll.ts
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/types/chat.ts
  src/utils/helpers.ts
Labels: development🔨

#331 경험치 페이지, 카테고리 추가 페이지
  src/apis/member.ts
  src/components/userSettings/ExpList.tsx
  src/constants/constants.ts
  src/hooks/query/category.ts
  src/hooks/query/member.ts
  src/hooks/useChatHandler.ts
  src/pages/channel/CategoryAddPage.tsx
  src/pages/userSettings/ExpHistoryPage.tsx
  src/types/apis/member.ts
  src/types/user.ts
  src/utils/formatters.ts
Labels: feature✨, development🔨

#328 라우트별 레이아웃 적용
  src/pages/RouterExampleDetailPage.tsx
  src/pages/RouterExamplePage.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
  src/router/lazy.ts
  src/styles/Layout.ts
Labels: refactor♻️, development🔨

#335 채팅 바텀시트 수정, 페이지별 패딩 수정
  src/components/chatting/ChatItem.tsx
  src/components/common/emoji/ChattingBottomsheet.tsx
  src/pages/channel/CategoryAddPage.tsx
  src/pages/channel/ChannelEditPage.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingProgressPage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/pages/userSettings/ExpHistoryPage.tsx
  src/pages/userSettings/SettingsPage.tsx
  src/router/Router.tsx
Labels: bug🐛, development🔨

#318 서버 정보 & 사이드바, Popover 컴포넌트
  src/apis/server.ts
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/common/Popover.tsx
  src/components/common/UserAvatar.tsx
  src/components/common/emoji/ChattingBottomsheet.tsx
  src/components/common/modal/CommunityDrawer.tsx
  src/components/common/modal/DeleteConfirmDialog.tsx
  src/components/community/CommunityInfoSection.tsx
  src/components/community/CommunitySettingSection.tsx
  src/components/community/ProfileModal.tsx
  src/hooks/query/server.ts
  src/hooks/useCopyToClipboard.ts
  src/hooks/usePopover.ts
  src/pages/communityinfosetting/CommunityInfoSettingPage.tsx
  src/types/apis/server.ts
Labels: refactor♻️, development🔨

#339 RecordDetailPage 페이지
  src/apis/record.ts
  src/apis/review.ts
  src/components/common/Header.tsx
  src/components/common/Tag.tsx
  src/components/library/BookDetail.tsx
  src/components/library/BookListItem.tsx
  src/components/library/Fieldset.tsx
  src/components/library/Header.tsx
  src/components/library/PageField.tsx
  src/components/library/PeriodField.tsx
  src/components/library/RecordBottomsheet.tsx
  src/components/library/ReviewBottomsheet.tsx
  src/components/library/ReviewDetail.tsx
  src/components/library/ReviewField.tsx
  src/components/library/ReviewListItem.tsx
  src/constants/routePath.ts
  src/constants/sessionStorage.ts
  src/hooks/query/book.ts
  src/hooks/query/record.ts
  src/hooks/query/review.ts
  src/pages/library/BookDetailPage.tsx
  src/pages/library/RecordDetailPage.tsx
  src/pages/library/RecordEditPage.tsx
  src/router/Router.tsx
  src/router/lazy.ts
  src/tests/apis/book.test.ts
  src/types/apis/record.ts
  src/types/apis/review.ts
  src/types/book.ts
  src/types/record.ts
  src/types/review.ts
Labels: feature✨, design💄

#324 Review 컴포넌트
  src/components/library/Review.tsx
Labels: feature✨, design💄

#341 🐛 에러 수정
  src/components/library/RecordListItem.tsx
  src/components/library/ReviewListItem.tsx
  src/components/library/StarReview.tsx
  src/pages/library/ReviewListPage.tsx
Labels: bug🐛

#337 수정 반영
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/common/UserProfile.tsx
  src/hooks/query/climbing.ts
  src/hooks/query/server.ts
  src/pages/library/LibraryHomePage.tsx
  src/types/climbing.ts
  src/types/user.ts
Labels: bug🐛, development🔨

#347 QA 버그 수정
  src/apis/interceptor.ts
  src/apis/member.ts
  src/components/channel/Carousel.tsx
  src/components/channel/ChannelItem.tsx
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/climbing/ClimbingRope.tsx
  src/components/climbing/MemoDialog.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/common/Accordion.tsx
  src/components/common/Header.tsx
  src/components/common/StatusBadgeListItem.tsx
  src/components/common/UserProfile.tsx
  src/components/common/emoji/ChattingBottomsheet.tsx
  src/components/userSettings/UserProfileImg.tsx
  src/hooks/query/category.ts
  src/hooks/useChatHandler.ts
  src/hooks/useDraggable.ts
  src/pages/channel/ChannelEditPage.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/channel/ChannelPage.tsx
  src/pages/chatting/ChattingListPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingPage.tsx
  src/pages/climbing/ClimbingPreparePage.tsx
  src/pages/userSettings/EditUserInfoPage.tsx
  src/states/atoms.ts
Labels: bug🐛, development🔨

#351 TextField 컴포넌트 flex-direction
  src/components/common/input/TextField.tsx
Labels: bug🐛, design💄

#344 레이아웃
  src/router/Layout.tsx
  src/router/Router.tsx
  src/styles/Layout.ts
Labels: bug🐛, design💄

#350 미디어 쿼리 max-width
  src/components/climbing/MemoDialog.tsx
  src/components/climbing/RecruitClimbingBottomSheet.tsx
  src/components/common/Header.tsx
  src/components/common/modal/CommunityDrawer.tsx
  src/components/common/modal/DeleteConfirmDialog.tsx
  src/components/community/CommunityInfoCard.tsx
  src/styles/global.ts
Labels: feature✨, design💄

#358 책 기록 상세 페이지
  src/apis/record.ts
  src/components/common/Fieldset.tsx
  src/components/common/Section.tsx
  src/components/common/Tag.tsx
  src/components/library/BookDetail.tsx
  src/components/library/PageField.tsx
  src/components/library/RatingField.tsx
  src/components/library/RecordBottomsheet.tsx
  src/components/library/RecordListItem.tsx
  src/components/library/Review.tsx
  src/components/library/ReviewBottomsheet.tsx
  src/components/library/ReviewDetail.tsx
  src/components/library/ReviewField.tsx
  src/components/library/ReviewListItem.tsx
  src/components/library/StatusField.tsx
  src/hooks/query/record.ts
  src/pages/channel/ChannelAddPage.tsx
  src/pages/climbing/ClimbingEditPage.tsx
  src/pages/library/RecordDetailPage.tsx
  src/pages/library/RecordListPage.tsx
  src/pages/library/SearchPage.tsx
  src/types/apis/record.ts
  src/utils/formatters.ts
Labels: refactor♻️, design💄

#360 QA 버그 수정
  src/apis/interceptor.ts
  src/components/channel/Carousel.tsx
  src/components/chatting/ChatBar.tsx
  src/components/common/Accordion.tsx
  src/components/common/Header.tsx
  src/hooks/useChatHandler.ts
  src/hooks/useDraggable.ts
  src/pages/channel/ChannelListPage.tsx
Labels: bug🐛, development🔨

#359 책 검색 페이지
  src/pages/library/SearchPage.tsx
  src/styles/reset.css
Labels: refactor♻️, design💄

#361 QA 수정 요청사항 반영
  src/components/channel/ChannelChatItem.tsx
  src/components/chatting/ChatBar.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChattingBottomsheet.tsx
  src/components/chatting/EmojiList.tsx
  src/components/climbing/ClimbingDescription.tsx
  src/components/climbing/ClimbingDetail.tsx
  src/components/climbing/ClimbingSummary.tsx
  src/components/climbing/CompleteCard.tsx
  src/components/climbing/EmojiBottomSheet.tsx
  src/components/climbing/EmojiList.tsx
  src/components/climbing/EmojiMemberListBottomSheet.tsx
  src/components/climbing/ParticipantList.tsx
  src/components/climbing/RecruitClimbingItem.tsx
  src/components/climbing/ReviewBoard.tsx
  src/components/climbing/ReviewItem.tsx
  src/components/common/Accordions.tsx
  src/components/common/EmojiItem.tsx
  src/components/common/UserAvatar.tsx
  src/components/common/modal/CommunityDrawer.tsx
  src/components/community/CommunityInfoCard.tsx
  src/components/community/CommunitySettingSection.tsx
  src/components/community/ProfileModal.tsx
  src/components/library/MountainImage.tsx
  src/constants/constants.ts
  src/hooks/query/climbing.ts
  src/hooks/query/member.ts
  src/pages/channel/ChannelPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/pages/library/LibraryHomePage.tsx
  src/types/apis/climbing.ts
Labels: bug🐛, development🔨

#363 QA 버그 해결
  src/components/library/ReviewListItem.tsx
  src/constants/constants.ts
  src/pages/addcommunity/AddCommunityPage.tsx
  src/pages/addcommunity/CheckInvitedCommunityPage.tsx
  src/pages/addcommunity/CreateNewCommunityPage.tsx
  src/pages/addcommunity/EnterInvitationPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/pages/communityinfosetting/CommunityInfoSettingPage.tsx
  src/pages/library/RecordListPage.tsx
Labels: bug🐛, design💄

#364 362 qa
  package.json
  src/apis/climbing.ts
  src/components/channel/ChannelChatBar.tsx
  src/components/chatting/ChannelChatBar.tsx
  src/components/climbing/ClimbingDetail.tsx
  src/components/climbing/ClimbingSummary.tsx
  src/components/climbing/CompleteCard.tsx
  src/components/common/Popover.tsx
  src/components/community/CommunitySettingSection.tsx
  src/components/errorBoundary/ErrorCatcher.tsx
  src/hooks/query/climbing.ts
  src/index.tsx
  src/pages/channel/ChannelListPage.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/types/apis/climbing.ts
Labels: bug🐛, development🔨

#368 hotfix
  src/pages/channel/ChannelAddPage.tsx
  src/styles/Layout.ts
Labels: bug🐛, design💄

#369 hotfix
  src/components/library/RecordListItem.tsx
  src/pages/library/RecordListPage.tsx
Labels: bug🐛, design💄

#370 hotfix
  src/components/common/input/Datepicker.tsx
  src/pages/channel/ChannelAddPage.tsx
  src/utils/helpers.ts
Labels: bug🐛, design💄

#371 메모 컴포넌트 수정, 클라이밍 페이지 레이아웃 수정
  src/components/climbing/Memo.tsx
  src/components/climbing/MemoDialog.tsx
  src/pages/climbing/ClimbingTerminatePage.tsx
  src/router/Router.tsx
Labels: bug🐛, development🔨
